// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFVfaxGPy1gLlM_j9_V65Ew_jv7laITE',
    appId: '1:1068002679557:web:6457c88d6f612744e8f56c',
    messagingSenderId: '1068002679557',
    projectId: 'jandosapp',
    authDomain: 'jandosapp.firebaseapp.com',
    databaseURL: 'https://jandosapp-default-rtdb.firebaseio.com',
    storageBucket: 'jandosapp.firebasestorage.app',
    measurementId: 'G-9L0JKLPP5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdjSuz1p6lTCPcEgwq3nfgKwHRK1wpD4',
    appId: '1:1068002679557:android:1a72d3acfc43a266e8f56c',
    messagingSenderId: '1068002679557',
    projectId: 'jandosapp',
    databaseURL: 'https://jandosapp-default-rtdb.firebaseio.com',
    storageBucket: 'jandosapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ZT6ND847kfQ73qqdhdoZO3xSwx-DUcY',
    appId: '1:1068002679557:ios:8d091cce1d04a182e8f56c',
    messagingSenderId: '1068002679557',
    projectId: 'jandosapp',
    databaseURL: 'https://jandosapp-default-rtdb.firebaseio.com',
    storageBucket: 'jandosapp.firebasestorage.app',
    iosBundleId: 'com.example.jandosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ZT6ND847kfQ73qqdhdoZO3xSwx-DUcY',
    appId: '1:1068002679557:ios:8d091cce1d04a182e8f56c',
    messagingSenderId: '1068002679557',
    projectId: 'jandosapp',
    databaseURL: 'https://jandosapp-default-rtdb.firebaseio.com',
    storageBucket: 'jandosapp.firebasestorage.app',
    iosBundleId: 'com.example.jandosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdFVfaxGPy1gLlM_j9_V65Ew_jv7laITE',
    appId: '1:1068002679557:web:8598c8821ecb7cf9e8f56c',
    messagingSenderId: '1068002679557',
    projectId: 'jandosapp',
    authDomain: 'jandosapp.firebaseapp.com',
    databaseURL: 'https://jandosapp-default-rtdb.firebaseio.com',
    storageBucket: 'jandosapp.firebasestorage.app',
    measurementId: 'G-595V6ZK99Y',
  );

}